"""
USAGE:
    python ./scripts/font_generate.py --font path/to/font.ttf --chars "abcdef"

Reads a monospace .ttf font file and measures upper and lower half pixel counts 
for each provided character to generate a C++ header file at ../src/font.h.
"""

import argparse
import os
from PIL import Image, ImageDraw, ImageFont
import numpy as np

def generate_font_header(font_path: str, char_set: str, font_size: int = 32, output_path: str = "../src/font.h"):
  # load monospace font
  font = ImageFont.truetype(font_path, font_size)
  
  # measure font metrics for cell height and width
  ascent, descent = font.getmetrics()
  height = ascent + descent
  width = int(font.getlength(char_set[0])) if char_set else font_size // 2

  pixels_upper = []
  pixels_lower = []

  mid = height // 2

  for c in char_set:
    # render character with white text on black background in greyscale
    img = Image.new("L", (width, height), color=0)
    draw = ImageDraw.Draw(img)
    draw.text((0, 0), c, font=font, fill=255, anchor="lt")

    # convert to float array normalized to [0, 1] per pixel
    arr = np.array(img, dtype=np.float64) / 255.0

    # partition horizontally into upper and lower half
    upper_half = arr[:mid, :]
    lower_half = arr[mid:, :]

    # accumulate fractional pixel counts
    pixels_upper.append(float(upper_half.sum()))
    pixels_lower.append(float(lower_half.sum()))

  # find global maximum count for normalization across both halves
  max_pixel = max(max(pixels_upper), max(pixels_lower))
  if max_pixel == 0:
    max_pixel = 1.0

  values_upper = [p / max_pixel for p in pixels_upper]
  values_lower = [p / max_pixel for p in pixels_lower]

  # escape characters for c++ string literal formatting
  escaped_char_set = ""
  for c in char_set:
    if c == '\\':
      escaped_char_set += "\\\\"
    elif c == '"':
      escaped_char_set += '\\"'
    elif c == '\n':
      escaped_char_set += "\\n"
    elif c == '\t':
      escaped_char_set += "\\t"
    else:
      escaped_char_set += c

  # format float arrays
  upper_str = ", ".join(f"{v:.6f}" for v in values_upper)
  lower_str = ", ".join(f"{v:.6f}" for v in values_lower)

  # write header file to target directory relative to ./scripts/
  os.makedirs(os.path.dirname(output_path), exist_ok=True)

  header_content = f"""// automatically generated by scripts/font_generate.py

#pragma once
#include <cstddef>

const size_t NUM_CHARS = {len(char_set)};
const char CHAR_SET[] = "{escaped_char_set}";

const double CHAR_UPPER[]{{{upper_str}}};

const double CHAR_LOWER[]{{{lower_str}}};
"""

  with open(output_path, "w", encoding="utf-8") as f:
    f.write(header_content)

if __name__ == "__main__":
  script_dir = os.path.dirname(os.path.abspath(__file__))

  # setup command line argument parsing
  parser = argparse.ArgumentParser(description="Generate header file with font pixel density features")
  parser.add_argument(
    "--font",
    help="Path to monospace .ttf font file",
    default=os.path.join(script_dir, "./fonts/comic_mono/ComicMono.ttf"),
  )
  parser.add_argument(
    "--chars",
    help="Character set to analyze",
    default=" !\"#$%&'*+,-.:;=?@~",
  )
  args = parser.parse_args()

  output_file = os.path.join(script_dir, "../src/font.h")

  generate_font_header(args.font, args.chars, output_path=output_file)
